wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.22.3
    framework: huggingface
    huggingface_version: 4.51.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1775157190
    t:
      1:
      - 1
      - 5
      - 11
      - 30
      - 41
      - 49
      - 53
      - 71
      - 95
      - 105
      2:
      - 1
      - 5
      - 11
      - 30
      - 41
      - 49
      - 53
      - 71
      - 95
      - 105
      3:
      - 2
      - 4
      - 7
      - 13
      - 42
      4: 3.10.16
      5: 0.22.3
      6: 4.51.3
      13: linux-x86_64
    e:
      ph54ft75unharqzog60f9os7wci6c3av:
        os: Linux-5.4.0-150-generic-x86_64-with-glibc2.27
        python: CPython 3.10.16
        started_at: '2026-04-02T19:13:10.591899Z'
        program: /home/ubuntu/cs336_assignments/assignment5-alignment/cs336_alignment/run_grpo.py
        code_path: cs336_alignment/run_grpo.py
        code_path_local: run_grpo.py
        git:
          remote_url: git@github.com:JPassionQ/assignment5-alignment.git
          commit: eb2c562e05802d3c9ee4c4ec2eec43b104d77e9e
        root: /home/ubuntu/cs336_assignments/assignment5-alignment/cs336_alignment
        host: jingqi
        executable: /home/ubuntu/anaconda3/envs/py310/bin/python
        cpu_count: 36
        cpu_count_logical: 32
        gpu_type: NVIDIA A100 80GB PCIe
        gpu_count: 2
        disk:
          /:
            total: '266717757440'
            used: '216703959040'
        memory:
          total: '64000000000'
        gpu_nvidia:
        - name: NVIDIA A100 80GB PCIe
          memory_total: '85899345920'
          cuda_cores: 6912
          architecture: Ampere
          uuid: GPU-4c5b4d92-df52-daad-7eb4-03eb33912af8
        - name: NVIDIA A100 80GB PCIe
          memory_total: '85899345920'
          cuda_cores: 6912
          architecture: Ampere
          uuid: GPU-fb328c3d-77de-fb7d-5d9b-1c13ab8c1419
        cuda_version: '12.3'
        writer_id: ph54ft75unharqzog60f9os7wci6c3av
    m:
    - 1: grpo_step
      6:
      - 3
    - 1: eval_step
      6:
      - 3
    - 1: train/reward_min
      5: 1
      6:
      - 1
    - 1: train/reward_mean
      5: 1
      6:
      - 1
    - 1: train/reward_max
      5: 1
      6:
      - 1
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/grad_norm
      5: 1
      6:
      - 1
    - 1: train/entropy
      5: 1
      6:
      - 1
    - 1: eval/avg_entropy
      5: 2
      6:
      - 1
    - 1: eval/avg_response_length
      5: 2
      6:
      - 1
    - 1: eval/avg_incorrect_res_length
      5: 2
      6:
      - 1
    - 1: eval/avg_correct_res_length
      5: 2
      6:
      - 1
    - 1: eval/accuracy
      5: 2
      6:
      - 1
